#!/bin/sh

# Prints the current volume or 🔇 if muted.

[ $(pamixer --get-mute) = true ] && echo '^C1^ﱝ^d^' && exit

vol="$(pamixer --get-volume)"

if [ "$vol" -gt "70" ]; then
	icon=""
elif [ "$vol" -lt "30" ]; then
	icon=""
else
	icon="墳"
fi

echo "^C4^$icon $vol%^d^"
