#!/bin/sh

# Show wifi 📶 and percent strength or 📡 if none.
# Show 🌐 if connected to ethernet or ❎ if none.
# Show 🔒 if a vpn connection is active

WIFI=$(nmcli -get-values IN-USE,SSID,SIGNAL device wifi list | grep '^\*')
NAME=$(echo "$WIFI" | cut -d: -f2)
SIGL=$(echo "$WIFI" | cut -d: -f3)

if [ -z "$WIFI" ]; then
	echo "^C8^睊 (0%)^d^"
else
	echo "^C2^直 $NAME ($SIGL%)^d^"
fi
